version: "3"
services:
  qrcode:
    build: .
    image: raskitoma/qrcode
    container_name: qrcode
    hostname: qrcode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guayaquil
      - PIXEL_WIDTH = 50
      - FG_COLOR = "#000000"
      - BG_COLOR = "#ffffff"      
    ports:
      - 8060:3000
    restart: always
